server:
  port: ${PORT:8080}
zuul:
  prefix: /api/v1
  routes:
    profile-api:
      path: /profile/**
    coupon-api:
      path: /coupon/**
eureka:
  client:
    register-with-eureka: false
    service-url:
      default-zone: ${EUREKA_URL:http://localhost:8761/eureka}
